[project]
name = "agora-server"
version = "0.1.0"
description = "Add a short description here"
authors = ["V <nandithebull@outlook.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
chromadb = "0.4.18.*"
flask = "3.0.0.*"
bleach = "6.1.0.*"
feedgen = "0.9.0.*"
feedparser = "6.0.10.*"
dateparser = "1.2.0.*"
marko = "2.0.2.*"
fuzzywuzzy = "0.18.0.*"
sqlalchemy = "2.0.23.*"
jsons = "1.6.3.*"
rdflib = "7.0.0.*"
python-dotenv = "1.0.0.*"
gitpython = "3.1.40.*"
flask_cors = "3.0.10.*"

[pypi-dependencies]
orgora = "*"
flask_wtf = "*"
